In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import make_classification 

In [4]:
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [5]:
X

array([[ 0.96479937, -0.06644898,  0.98676805, ..., -1.2101605 ,
        -0.62807677,  1.22727382],
       [-0.91651053, -0.56639459, -1.00861409, ..., -0.98453405,
         0.36389642,  0.20947008],
       [-0.10948373, -0.43277388, -0.4576493 , ..., -0.2463834 ,
        -1.05814521, -0.29737608],
       ...,
       [ 1.67463306,  1.75493307,  1.58615382, ...,  0.69272276,
        -1.50384972,  0.22526412],
       [-0.77860873, -0.83568901, -0.19484228, ..., -0.49735437,
         2.47213818,  0.86718741],
       [ 0.24845351, -1.0034389 ,  0.36046013, ...,  0.77323999,
         0.1857344 ,  1.41641179]], shape=(1000, 10))

In [6]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    0.964799 -0.066449  0.986768 -0.358079  0.997266  1.181890 -1.615679   
1   -0.916511 -0.566395 -1.008614  0.831617 -1.176962  1.820544  1.752375   
2   -0.109484 -0.432774 -0.457649  0.793818 -0.268646 -1.836360  1.239086   
3    1.750412  2.023606  1.688159  0.006800 -1.607661  0.184741 -2.619427   
4   -0.224726 -0.711303 -0.220778  0.117124  1.536061  0.597538  0.348645   
..        ...       ...       ...       ...       ...       ...       ...   
995 -1.367638  1.462255 -1.154918 -0.290454 -0.413424  0.032396  1.545490   
996 -1.514876 -3.221016 -1.300744  0.395599 -0.527994  1.353069  1.777506   
997  1.674633  1.754933  1.586154  0.018402 -1.514470  0.321593 -2.417694   
998 -0.778609 -0.835689 -0.194842  1.097220  0.180071 -0.272933 -0.533188   
999  0.248454 -1.003439  0.360460 -0.331352  1.389764 -1.345210 -0.740875   

            7         8         9  
0   -1.210161 -0.628077  1.227274  
1   -0.984534  0.363896  0.209470  
2   -0.246383 -1.058145 -0.297376  
3   -0.357445 -1.473127 -0.190039  
4   -0.939156  0.175915  0.236224  
..        ...       ...       ...  
995  1.428760  1.687092  1.072542  
996 -1.680870  1.798510  0.034272  
997  0.692723 -1.503850  0.225264  
998 -0.497354  2.472138  0.867187  
999  0.773240  0.185734  1.416412  

[1000 rows x 10 columns]

In [7]:
pd.DataFrame(y)

0
0    0
1    1
2    1
3    0
4    1
..  ..
995  1
996  1
997  0
998  0
999  0

[1000 rows x 1 columns]

In [8]:
from pandas._typing import RandomState
from numpy.matlib import rand
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
X_train

array([[-6.39262431e-02, -2.21042464e-01,  1.89653652e-01, ...,
         2.39210964e+00,  8.74894567e-01,  1.92596919e-01],
       [-1.88464871e+00,  9.20551373e-02, -1.61923889e+00, ...,
        -9.93593004e-01,  2.23427922e+00,  2.52992775e+00],
       [ 5.31307386e-01,  2.65362349e-01,  3.71714169e-01, ...,
        -1.34279162e-01, -9.06844611e-01, -2.43881716e+00],
       ...,
       [ 4.09146664e-02,  4.27962627e-01, -2.35298234e-03, ...,
        -1.92277177e+00, -1.71047718e-01,  1.63925652e+00],
       [ 3.39379203e-01, -6.40154457e-01,  2.52539950e-01, ...,
        -1.39922826e+00, -5.29912480e-01, -7.34810898e-01],
       [ 1.84815207e+00, -3.13058031e-01,  1.78069642e+00, ...,
         6.04515326e-01, -1.56102804e+00, -1.25040773e+00]],
      shape=(800, 10))

In [10]:
X_test

array([[ 0.74030596,  0.42548993,  0.6039124 , ..., -0.709441  ,
        -0.98264957, -1.3716737 ],
       [-1.49577819,  0.38135283, -1.2763343 , ...,  0.57404193,
         1.80201193, -0.63014283],
       [-0.14407863, -0.00928856,  0.02366179, ..., -0.34287886,
         0.65257238,  1.8134077 ],
       ...,
       [-0.04826718, -0.66834519, -0.36749269, ..., -2.49806102,
        -1.00799498, -1.05844063],
       [-0.35347622,  0.25719897, -0.73499374, ..., -0.32561105,
        -0.99012668,  0.00788018],
       [-0.05779027, -0.64982689, -0.67262375, ...,  0.47982704,
        -1.96692876,  0.01282864]], shape=(200, 10))

In [12]:
y_test

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1])