In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.datasets import make_classification 

In [4]:
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [5]:
X

array([[ 0.96479937, -0.06644898,  0.98676805, ..., -1.2101605 ,
        -0.62807677,  1.22727382],
       [-0.91651053, -0.56639459, -1.00861409, ..., -0.98453405,
         0.36389642,  0.20947008],
       [-0.10948373, -0.43277388, -0.4576493 , ..., -0.2463834 ,
        -1.05814521, -0.29737608],
       ...,
       [ 1.67463306,  1.75493307,  1.58615382, ...,  0.69272276,
        -1.50384972,  0.22526412],
       [-0.77860873, -0.83568901, -0.19484228, ..., -0.49735437,
         2.47213818,  0.86718741],
       [ 0.24845351, -1.0034389 ,  0.36046013, ...,  0.77323999,
         0.1857344 ,  1.41641179]], shape=(1000, 10))

In [6]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    0.964799 -0.066449  0.986768 -0.358079  0.997266  1.181890 -1.615679   
1   -0.916511 -0.566395 -1.008614  0.831617 -1.176962  1.820544  1.752375   
2   -0.109484 -0.432774 -0.457649  0.793818 -0.268646 -1.836360  1.239086   
3    1.750412  2.023606  1.688159  0.006800 -1.607661  0.184741 -2.619427   
4   -0.224726 -0.711303 -0.220778  0.117124  1.536061  0.597538  0.348645   
..        ...       ...       ...       ...       ...       ...       ...   
995 -1.367638  1.462255 -1.154918 -0.290454 -0.413424  0.032396  1.545490   
996 -1.514876 -3.221016 -1.300744  0.395599 -0.527994  1.353069  1.777506   
997  1.674633  1.754933  1.586154  0.018402 -1.514470  0.321593 -2.417694   
998 -0.778609 -0.835689 -0.194842  1.097220  0.180071 -0.272933 -0.533188   
999  0.248454 -1.003439  0.360460 -0.331352  1.389764 -1.345210 -0.740875   

            7         8         9  
0   -1.210161 -0.628077  1.227274  
1   -0.984534  0.363896  0.209470  
2   -0.246383 -1.058145 -0.297376  
3   -0.357445 -1.473127 -0.190039  
4   -0.939156  0.175915  0.236224  
..        ...       ...       ...  
995  1.428760  1.687092  1.072542  
996 -1.680870  1.798510  0.034272  
997  0.692723 -1.503850  0.225264  
998 -0.497354  2.472138  0.867187  
999  0.773240  0.185734  1.416412  

[1000 rows x 10 columns]

In [7]:
pd.DataFrame(y)

0
0    0
1    1
2    1
3    0
4    1
..  ..
995  1
996  1
997  0
998  0
999  0

[1000 rows x 1 columns]

In [8]:
from pandas._typing import RandomState
from numpy.matlib import rand
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
X_train

array([[-6.39262431e-02, -2.21042464e-01,  1.89653652e-01, ...,
         2.39210964e+00,  8.74894567e-01,  1.92596919e-01],
       [-1.88464871e+00,  9.20551373e-02, -1.61923889e+00, ...,
        -9.93593004e-01,  2.23427922e+00,  2.52992775e+00],
       [ 5.31307386e-01,  2.65362349e-01,  3.71714169e-01, ...,
        -1.34279162e-01, -9.06844611e-01, -2.43881716e+00],
       ...,
       [ 4.09146664e-02,  4.27962627e-01, -2.35298234e-03, ...,
        -1.92277177e+00, -1.71047718e-01,  1.63925652e+00],
       [ 3.39379203e-01, -6.40154457e-01,  2.52539950e-01, ...,
        -1.39922826e+00, -5.29912480e-01, -7.34810898e-01],
       [ 1.84815207e+00, -3.13058031e-01,  1.78069642e+00, ...,
         6.04515326e-01, -1.56102804e+00, -1.25040773e+00]],
      shape=(800, 10))

In [10]:
X_test

array([[ 0.74030596,  0.42548993,  0.6039124 , ..., -0.709441  ,
        -0.98264957, -1.3716737 ],
       [-1.49577819,  0.38135283, -1.2763343 , ...,  0.57404193,
         1.80201193, -0.63014283],
       [-0.14407863, -0.00928856,  0.02366179, ..., -0.34287886,
         0.65257238,  1.8134077 ],
       ...,
       [-0.04826718, -0.66834519, -0.36749269, ..., -2.49806102,
        -1.00799498, -1.05844063],
       [-0.35347622,  0.25719897, -0.73499374, ..., -0.32561105,
        -0.99012668,  0.00788018],
       [-0.05779027, -0.64982689, -0.67262375, ...,  0.47982704,
        -1.96692876,  0.01282864]], shape=(200, 10))

In [11]:
y_test

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1])

In [12]:
from sklearn.linear_model import LogisticRegression

regression = LogisticRegression()

In [13]:
regression.fit(X_train,y_train)

LogisticRegression()

In [14]:
y_pred = regression.predict(X_test)

In [15]:
y_pred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1])

In [16]:
y_pred_prob = regression.predict_proba(X_test)
y_pred_prob

array([[7.78600959e-01, 2.21399041e-01],
       [3.19099883e-02, 9.68090012e-01],
       [6.42146681e-01, 3.57853319e-01],
       [7.47380192e-02, 9.25261981e-01],
       [9.75407948e-01, 2.45920523e-02],
       [3.99148910e-02, 9.60085109e-01],
       [9.78737182e-01, 2.12628178e-02],
       [9.52833227e-01, 4.71667733e-02],
       [7.87837418e-01, 2.12162582e-01],
       [6.81333736e-01, 3.18666264e-01],
       [9.15901071e-01, 8.40989288e-02],
       [2.42589360e-01, 7.57410640e-01],
       [5.03410713e-01, 4.96589287e-01],
       [1.92363097e-01, 8.07636903e-01],
       [7.93085129e-01, 2.06914871e-01],
       [9.43576898e-01, 5.64231015e-02],
       [2.69367304e-02, 9.73063270e-01],
       [3.41710994e-01, 6.58289006e-01],
       [3.08678280e-01, 6.91321720e-01],
       [1.74169127e-01, 8.25830873e-01],
       [4.84677714e-01, 5.15322286e-01],
       [9.62607338e-01, 3.73926615e-02],
       [1.81990356e-01, 8.18009644e-01],
       [7.82536737e-01, 2.17463263e-01],
       [8.635545

In [17]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [18]:
score = accuracy_score(y_test,y_pred)
print(f"Accuracy : {score}")
cm = confusion_matrix(y_test,y_pred)
print(f"Confusion matrix : {cm}")
opm = classification_report(y_test,y_pred)
print(f"{opm}")

Accuracy : 0.83
Confusion matrix : [[75 14]
 [20 91]]
              precision    recall  f1-score   support

           0       0.79      0.84      0.82        89
           1       0.87      0.82      0.84       111

    accuracy                           0.83       200
   macro avg       0.83      0.83      0.83       200
weighted avg       0.83      0.83      0.83       200



In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
penalty = ['l1','l2','elasticnet']
c_values = [100,10,1.0,0.1,0.01]
solver = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']

In [21]:
params = dict(penalty=penalty, C=c_values , solver = solver)

In [22]:
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold()

In [23]:
grid = GridSearchCV(estimator = regression , param_grid=params , cv=cv , scoring='accuracy' , n_jobs=-1)

In [24]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [25]:
grid.fit(X_train,y_train)

d:\ML-DL-NLP\Machine Learning\.venv\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
250 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ML-DL-NLP\Machine Learning\.venv\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\ML-DL-NLP\Machine Learning\.venv\lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "d:\ML-DL-NLP\Machine Learning\.venv\lib\site-packages\sklearn\linear_model\_logistic.py", line 1218, in fit
    solver = _chec

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [26]:
grid.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'liblinear'}

In [27]:
grid.best_score_

np.float64(0.8787500000000001)

In [28]:
better_model = LogisticRegression(penalty='l2',C=0.01,solver='liblinear')

In [29]:
better_model.fit(X_train,y_train)

LogisticRegression(C=0.01, solver='liblinear')

In [34]:
y_pred_b = grid.predict(X_test)

In [35]:
print(f"Score of normal model : ")
score = accuracy_score(y_test,y_pred)
print(f"Accuracy : {score}")
cm = confusion_matrix(y_test,y_pred)
print(f"Confusion matrix : {cm}")
opm = classification_report(y_test,y_pred)
print(f"{opm}")
print()
print(f"Score of hyperparameter tuned model : ")
score1 = accuracy_score(y_test,y_pred_b)
print(f"Accuracy : {score1}")
cm1 = confusion_matrix(y_test,y_pred_b)
print(f"Confusion matrix : {cm1}")
opm1 = classification_report(y_test,y_pred_b)
print(f"{opm1}")


Score of normal model : 
Accuracy : 0.83
Confusion matrix : [[75 14]
 [20 91]]
              precision    recall  f1-score   support

           0       0.79      0.84      0.82        89
           1       0.87      0.82      0.84       111

    accuracy                           0.83       200
   macro avg       0.83      0.83      0.83       200
weighted avg       0.83      0.83      0.83       200


Score of hyperparameter tuned model : 
Accuracy : 0.825
Confusion matrix : [[78 11]
 [24 87]]
              precision    recall  f1-score   support

           0       0.76      0.88      0.82        89
           1       0.89      0.78      0.83       111

    accuracy                           0.82       200
   macro avg       0.83      0.83      0.82       200
weighted avg       0.83      0.82      0.83       200



In [36]:
from sklearn.model_selection import RandomizedSearchCV

In [37]:
rcv = RandomizedSearchCV(estimator=regression,param_distributions=params,cv=cv,scoring='accuracy')

In [38]:
rcv

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [41]:
rcv.fit(X_train,y_train)

d:\ML-DL-NLP\Machine Learning\.venv\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
35 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ML-DL-NLP\Machine Learning\.venv\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\ML-DL-NLP\Machine Learning\.venv\lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "d:\ML-DL-NLP\Machine Learning\.venv\lib\site-packages\sklearn\linear_model\_logistic.py", line 1218, in fit
    solver = _check_

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [42]:
rcv.best_params_

{'solver': 'newton-cholesky', 'penalty': 'l2', 'C': 0.01}

In [43]:
y_pred_r = rcv.predict(X_test)

In [44]:
print(f"Score of normal model : ")
score = accuracy_score(y_test,y_pred)
print(f"Accuracy : {score}")
cm = confusion_matrix(y_test,y_pred)
print(f"Confusion matrix : {cm}")
opm = classification_report(y_test,y_pred)
print(f"{opm}")
print()
print(f"Score of hyperparameter tuned model : ")
score1 = accuracy_score(y_test,y_pred_b)
print(f"Accuracy : {score1}")
cm1 = confusion_matrix(y_test,y_pred_b)
print(f"Confusion matrix : {cm1}")
opm1 = classification_report(y_test,y_pred_b)
print(f"{opm1}")
print()
print(f"Score of hyperparameter tuned model 2 : ")
score2 = accuracy_score(y_test,y_pred_r)
print(f"Accuracy : {score2}")
cm2 = confusion_matrix(y_test,y_pred_r)
print(f"Confusion matrix : {cm2}")
opm2 = classification_report(y_test,y_pred_r)
print(f"{opm2}")


Score of normal model : 
Accuracy : 0.83
Confusion matrix : [[75 14]
 [20 91]]
              precision    recall  f1-score   support

           0       0.79      0.84      0.82        89
           1       0.87      0.82      0.84       111

    accuracy                           0.83       200
   macro avg       0.83      0.83      0.83       200
weighted avg       0.83      0.83      0.83       200


Score of hyperparameter tuned model : 
Accuracy : 0.825
Confusion matrix : [[78 11]
 [24 87]]
              precision    recall  f1-score   support

           0       0.76      0.88      0.82        89
           1       0.89      0.78      0.83       111

    accuracy                           0.82       200
   macro avg       0.83      0.83      0.82       200
weighted avg       0.83      0.82      0.83       200


Score of hyperparameter tuned model 2 : 
Accuracy : 0.825
Confusion matrix : [[78 11]
 [24 87]]
              precision    recall  f1-score   support

           0       0